### ISSUE TITLE
R.java

### ISSUE THREAD

**Issue by Shusshu** [Shusshu/maven-android-plugin#2]
From ialbors:

```
 I've created this sample project (with gridlayout-v7.aar and actionbarsherlock as apklib):

https://github.com/ialbors/android-m-p_aar_testproject

mvn clean package
grep 0x7f030000 -r target/
target/generated-sources/r/android/support/v7/gridlayout/R.java: 
public static final int default_gap=0x7f030000;

target/generated-sources/r/com/actionbarsherlock/R.java:
public static int abs__action_bar_home=0x7f030000;

target/generated-sources/r/test/R.java:
public static final int abs__action_bar_home=0x7f030000;

They all have the same id (0x7f030000) but they are different attributes.
```

**Comment by Shusshu** [comment]
I have forked your example and changed it a bit.

https://github.com/Shusshu/android-m-p_aar_testproject

I tried different things using 2 aars (gridlayout & actionbarsherlock)

A. the dependency gridlayout is followed by actionbarsherlock (both aar)

the R.java of actionbarsherlock is empty
The default_gap has a diff value (different from the gradle one but also diff from the other fields in the R class)

B. the dependency actionbarsherlock is followed by gridlayout (both aar)

the R.java of gridlayout is empty

The default_gap has a diff value (different from the gradle one but also diff from the other fields in the R class)

C. your own result with gridlayout aar & actionbarsherlock apklib

**Comment by Shusshu** [comment]
At least one thing is working

if you only put actionbarsherlock as an aar everything is created properly

**Comment by Shusshu** [comment]
good to look into AndroidBuilder's code
https://android.googlesource.com/platform/tools/build/+/master/builder/src/main/java/com/android/builder/AndroidBuilder.java  line 700 and other places

**Comment by ialbors** [comment]
Ok. I've tested with both aar and same results.

But I don't really know if it's right to have an empty R.java (gridlayout or actionbarsherlock). It seems to merge it in the app's R.java, right? But I'm not sure it's the way it's supposed to be.

I will try to test it in a real app.

**Comment by Shusshu** [comment]
Nope it's not supposed to be like that. something is wrong but I have no
idea what :)

Benoit Billington

**Comment by ialbors** [comment]
Got something!!

fullSymbolValues has to be loaded with the app's R.txt, not the library one.

So, I think the approach shoul be something like:
1. Add the switch "--output-text-symbols target/ [or whatever directory is the standard for it]"  to the aapt command when creating app's R.java.
2. Patch your code with somethin like this (here "/target/R.txt" is hardcoded)

<pre>
diff --git a/src/main/java/com/jayway/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java b/src/main/java/com/jayway/maven/plugins/android/phase01generatesources/
index cf6f625..b8d61a3 100644
--- a/src/main/java/com/jayway/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java
+++ b/src/main/java/com/jayway/maven/plugins/android/phase01generatesources/GenerateSourcesMojo.java
@@ -708,7 +708,7 @@ public class GenerateSourcesMojo extends AbstractAndroidMojo
                     // resources anywhere.
                     if ( fullSymbolValues == null )
                     {
-                        fullSymbolValues = new SymbolLoader( rFile, null );
+                        fullSymbolValues = new SymbolLoader( new File( "./target/R.txt" ), null );
 
                         fullSymbolValues.load();
                     }
</pre>

What do you think?

**Comment by Shusshu** [comment]
Oh I also did something damn

**Comment by ialbors** [comment]
Hehehehe... That's fine, whatever works

**Comment by ialbors** [comment]
Hey! It seems to work with apklibs too.

**Comment by Shusshu** [comment]
pull request done https://github.com/jayway/maven-android-plugin/pull/249
